### ISSUE TITLE
Subsequent csv files are getting data of previous files

### ISSUE THREAD

**Issue by rohitmanglik** [rohitmanglik/scrap-preprocessor#11]
We have two csv files in demo.
updated_small.csv is getting data of updated_sample.csv as well,

**Comment by rohitmanglik** [comment]
Just verified, issue is not yet resolved.

**Comment by mohitreddy1996** [comment]
Found the mistake.
processed data itself is getting updated incorrectly.
we just extend self.ROWS. So it contains the data of sample also.

**Comment by mohitreddy1996** [comment]
Pushed the change.
After cross checking, Do close the issue.

**Comment by anantharam** [comment]
It is clearing the row cache on each run now.
