### ISSUE TITLE
Case: Lat and Long are zero

### ISSUE THREAD

**Issue by rohitmanglik** [rohitmanglik/scrap-preprocessor#15]
In case Latitude and Longitude are zero, change Latitude and Longitude to a location in their respective city.

**Comment by shubhiD** [comment]
Issue is resolved hence closing

**Comment by rohitmanglik** [comment]
Did you add an extra column for it? What's the column name? I am unable to find it.

**Comment by shubhiD** [comment]
No till now I haven't
