### ISSUE TITLE
Lat and Long - not precise

### ISSUE THREAD

**Issue by rohitmanglik** [rohitmanglik/scrap-preprocessor#18]
Right now Lat and Long are completed screwed up. Make sure data is precise. It is showing same lat and long for most of the entries. Revert back the code if required. 

Make sure Lat and Long are correct for at least 70 out of 77 records. For other 7 we can use city lat and long.

**Comment by rohitmanglik** [comment]
If value is not set in "Precise" column -> It's not precise.

With latest code changes, we have a huge success ratio. I am not sure whether we can still improve the lat and long.

Further improvement will require these issues to be solved: Autocomplete API and Bing Maps Search, so let's hold on to this.

**Comment by rohitmanglik** [comment]
In the latest file, NIKS Academy has lat and long as list index out of range 22.7258984, 75.887389. These values are more than 1 degree far from city. Please check.

**Comment by shubhiD** [comment]
Thats why prec_loc is not marked true

**Comment by rohitmanglik** [comment]
I mean as per our code, if their location is way far from city lat and long, they should be assigned city's lat and long. - this part of logic hasn't worked with a few entries.

**Comment by shubhiD** [comment]
fixed
