### ISSUE TITLE
Case of no image

### ISSUE THREAD

**Issue by rohitmanglik** [rohitmanglik/scrap-preprocessor#19]
At the end of al the processing, some of the places will not have any image.

In such case, create a new image as featured image. - assign that image only in featured image. Don't assign it to Images URL or listing_gallery columns.

We are open for suggestions of the way image should be constructed.

Thanks

**Comment by rohitmanglik** [comment]
Way 1: First Character of Name with a cool background color- just the way GMail does it

Way 2: Name of whole Institute with some cool background color.

The featured image will replace "?" at http://directory.edudrona.com/location/agra/.
Size of image must be atleast 200px*200px.

**Comment by rohitmanglik** [comment]
I am getting this error during compilation:

  File "geocodertest.py", line 187, in <module>
    f.process()
  File "geocodertest.py", line 49, in process
    self._addFeaturedImage();
  File "geocodertest.py", line 159, in _addFeaturedImage
    row['featured_image'] = fetch(row['Name']); #creates png image
  File "/home/user/scrap-preprocessor/imagesFetch.py", line 13, in fetch
    fnt=ImageFont.truetype('Pillow/Tests/fonts/FreeMonoBold.ttf',50)
  File "/usr/local/lib/python2.7/dist-packages/PIL/ImageFont.py", line 239, in truetype
    return FreeTypeFont(font, size, index, encoding)
  File "/usr/local/lib/python2.7/dist-packages/PIL/ImageFont.py", line 128, in __init__
    self.font = core.getfont(font, size, index, encoding)
IOError: cannot open resource
1

**Comment by shubhiD** [comment]
have you installed PIL? And there is a new imagesFetch.py file I created

**Comment by rohitmanglik** [comment]
Just a small change - put these images in listing_gallery and images URL as well - if the field is empty.

**Comment by rohitmanglik** [comment]
After changes applied: http://directory.edudrona.com/location/agra/?sort-by=published

**Comment by rohitmanglik** [comment]
Passed all the test cases, just ned to improve image quality.

**Comment by shubhiD** [comment]
500*500 would suffice?

**Comment by rohitmanglik** [comment]
Even 250*250 is a good image but it's still getting blurred. Yes, let's try with 500*500.

**Comment by rohitmanglik** [comment]
Verified the fix.

**Comment by rohitmanglik** [comment]
@shubhiD Just now I ran the code but I am unable to get images of Ahmedabad Institutes (images of Agra Institutes are already present).

Code is broken somewhere.

**Comment by shubhiD** [comment]
can you send the csv file of Ahmdabad institutes?

**Comment by rohitmanglik** [comment]
It's in the input folder.

**Comment by shubhiD** [comment]
the png images are not created right?

**Comment by rohitmanglik** [comment]
Yes

**Comment by shubhiD** [comment]
Can I have the output file as well?

**Comment by rohitmanglik** [comment]
Committed.

**Comment by rohitmanglik** [comment]
Tested the fix
