### ISSUE TITLE
Search in Google Images for Institute Photos

### ISSUE THREAD

**Issue by rohitmanglik** [rohitmanglik/scrap-preprocessor#20]
This step should be after we are done with Google Maps API, http://www.panoramio.com/, Google Places etc. 

In case no images are found in above result, get top 5 images from Google Image Search.

**Comment by shubhiD** [comment]
I guess crawling is prohibited on google and may be will have to deal with captcha though not sure others please comment

**Comment by rohitmanglik** [comment]
Closing as there is no update.
