### ISSUE TITLE
Encoding error for using str to convert from Unicode into Text

### ISSUE THREAD

**Issue by shashwat-vik** [rohitmanglik/scrap-preprocessor#28]
**Instead of using str() directly, .encode() should be used to encode the string.
Getting the following error.**

> Processed 940 rows.
> Processed 960 rows.
> Processed 980 rows.
> Processed 1000 rows.
> Successfully completed processing of (1001/1001) rows.
> Adding rating and reviews
> Traceback (most recent call last):
>   File "geocodertest.py", line 221, in <module>
>     f.process()
>   File "geocodertest.py", line 49, in process
>     self._addLocationPhoto();
>   File "geocodertest.py", line 174, in _addLocationPhoto
>     f._addRatingsReviews(details_reviews,row)
>   File "geocodertest.py", line 196, in _addRatingsReviews
>     row['reviews']+=str(reviews[i]['text'])+","
> UnicodeEncodeError: 'ascii' codec can't encode character u'\u202a' in position 29: ordinal not in range(128)

**Comment by rohitmanglik** [comment]
Refer http://stackoverflow.com/questions/9942594/unicodeencodeerror-ascii-codec-cant-encode-character-u-xa0-in-position-20
