### ISSUE TITLE
Download Images

### ISSUE THREAD

**Issue by rohitmanglik** [rohitmanglik/scrap-preprocessor#3]
As discussed with Erik (Superlist Author), Integration of WP Import All is not completely finished. We have to go with CSV import all for sometime. So need to do following functionality: 

a) Download all the image mentioned in images column and save in a folder
b) Rename them to "{hash value}.{file format}"
c) Update image url in CSV file to the new filename
d) Zip all the files.

**Comment by rohitmanglik** [comment]
`a:5:{i:1006;s:111:"http://preview.byaviators.com/theme/superlist/wp-content/uploadz/2015/10/photo-1425243749210-c3e3c231504d1.jpeg";i:1007;s:110:"http://preview.byaviators.com/theme/superlist/wp-content/uploadz/2015/10/photo-1441154283565-f88df169765a.jpeg";i:779;s:110:"http://preview.byaviators.com/theme/superlist/wp-content/uploadz/2015/10/photo-1428470341793-f73b1237fb98.jpeg";i:628;s:109:"http://preview.byaviators.com/theme/superlist/wp-content/uploadz/2015/09/yjA2So4sRtmdLFRSkD5t_moulin-fisk.jpg";i:1010;s:110:"http://preview.byaviators.com/theme/superlist/wp-content/uploadz/2015/10/photo-1433416718482-9d0ff44c5460.jpeg";}`

-for gallery

**Comment by rohitmanglik** [comment]
Linked Thread: https://wordpress.org/support/topic/import-image-gallery?replies=2#post-8771608

**Comment by abhikrsagar** [comment]
So if I have understood the problem correctly then it is that I will be given a csv file containing image URlLs to be downloaded.I have to download the images,rename them as hashvalue.extension.But what do you mean by updating image url in CSV file.Do we have to convert web based URL into localhost based URL or else if we updated the URL by modifying the file name in the CSV then that URL would become invalid and it cant be used later on.

**Comment by rohitmanglik** [comment]
@abhikrsagar this issue has to be resolved by a third party plugin. Might be you can look into any issue of https://github.com/rohitmanglik/scrap_careers

**Comment by rohitmanglik** [comment]
@anantharam we have to change format of listing_gallery in above serialized string.

**Comment by rohitmanglik** [comment]
We had to write PHP Code in Step 3 to resolve this issue.

**Comment by rohitmanglik** [comment]
A small bug: only 3 images are shown.

**Comment by rohitmanglik** [comment]
Fixed the changes in server
