### ISSUE TITLE
Duplicate columns

### ISSUE THREAD

**Issue by rohitmanglik** [rohitmanglik/scrap-preprocessor#4]
I wrote an email to Erik, asking to merge duplicate and unnecessary columns. 

If he doesn't do it, we have to manually create following columns to decrease manual effort:

listing_banner_map_marker
listing_banner_map_type
listing_banner_map_zoom
listing_inside_view_location
listing_inside_view_location_latitude
listing_inside_view_location_longitude
listing_inside_view_location_zoom
listing_google_street_view_latitude
listing_google_street_view_longitude
listing_google_street_view_zoom
listing_banner_street_view_latitude
listing_banner_street_view_longitude
listing_banner_street_view_zoom

Let's wait for the Author to reply

**Comment by eriktelepovsky** [comment]
Hi, none of these columns are duplicates. Each of banner, inside view, google street view and banner street view can have set different latitude, longitude or zoom.

**Comment by rohitmanglik** [comment]
listing_banner_map_marker
listing_banner_map_type
listing_banner_map_zoom
listing_inside_view_location
listing_inside_view_location_latitude: latitude
listing_inside_view_location_longitude: longitude
listing_inside_view_location_zoom: 16
listing_google_street_view_latitude
listing_google_street_view_longitude
listing_google_street_view_zoom: 16
listing_banner_street_view_latitude
listing_banner_street_view_longitude
listing_banner_street_view_zoom:16

**Comment by rohitmanglik** [comment]
New column name - old column name
post_title - name
post_content - about
post_name - name

claim_email - mail
claim_name - person to contact
claim_phone - phone

Listing_description - about

listing_address - address
listing_email - email
listing_gallery - Images URL
listing_google - address  - WRONG
listing_google_street_view - address
listing_google_map - address
listing_phone - phone
listing_inside_view_location - put location tag
listing_map_location - address
listing_street_view_location - put location tag

post_category - services offered
post_tag - services offered
categories - Services offered

**Comment by rohitmanglik** [comment]
Everything is done - awaiting final testing
