### ISSUE TITLE
Error while processing CSV file: Ahmedabad

### ISSUE THREAD

**Issue by rohitmanglik** [rohitmanglik/scrap-preprocessor#41]
In middle of console output, I got following errors:

	Group Tuition
	Adding rating and reviews
	New Info Added from Facebook
	Details:64 Facebook Link:263 Cover:193
	Website:72 Pincode:0 Address:30 Images:0
	09/25/2016 01:13:50 PM ERROR: Something awful happened when processing result.csv
	Traceback (most recent call last):
	  File "geocodertest.py", line 320, in _writeCSV
		writer.writerow(row)
	  File "/usr/lib/python2.7/csv.py", line 152, in writerow
		return self.writer.writerow(self._dict_to_list(rowdict))
	UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 828: ordinal not in range(128)
	***Successfully processed 1 files.***

**Comment by gupta-shantanu** [comment]
@shubhiD is this error fixed now?

**Comment by shubhiD** [comment]
nope

**Comment by rohitmanglik** [comment]
@gupta-shantanu did you have a fix for this issue?

**Comment by gupta-shantanu** [comment]
@rohitmanglik we can encode everything in utf-8 before writing, but better solution would be to check which API is returning this character and deal with it there. I was unable to trace exact record for which it fails. File is too big and my connection is slow, @shashwat-vik can you help?

**Comment by shubhiD** [comment]
I am thinking of encoding dict values and keys just before writing to csv

On Oct 1, 2016 5:14 PM, "shantanu gupta" <notifications@github.com> wrote:

@rohitmanglik <https://github.com/rohitmanglik> we can encode everything in
utf-8 before writing, but better solution would be to check which API is
returning this character and deal with it there. I was unable to trace
exact record for which it fails. File is too big and my connection is slow,
@shashwat-vik <https://github.com/shashwat-vik> can you help?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/rohitmanglik/scrap-preprocessor/issues/41#issuecomment-250908084>,
or mute the thread

**Comment by shubhiD** [comment]
The last time I checked I think the error was from fbGraph.py

**Comment by rohitmanglik** [comment]
Still getting error while processing csv file.

**Comment by rohitmanglik** [comment]
10/02/2016 08:20:43 AM ERROR: Something awful happened when processing result.csv
	Traceback (most recent call last):
	  File "geocodertest.py", line 216, in _writeCSV
		writer.writerow(row)
	  File "/usr/lib/python2.7/csv.py", line 152, in writerow
		return self.writer.writerow(self._dict_to_list(rowdict))
	UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 58: ordinal not in range(128)

**Comment by gupta-shantanu** [comment]
@shubhiD I coudn't trace this new error in fbGraph (though last time it existed in street address field returned by fb). Please help me recreate the error (give the record number or name for which error occurs).
If problem has multiple source, I guess we should encode all the fields and records.

**Comment by rohitmanglik** [comment]
Latest console output:

	bitnami@ip-172-31-4-116:~/rohit/scrap-preprocessor$ python main.py
	['./input/sample_big.csv']

	RUNNING AUTOCOMPLETE
	100%

	####################
	FIXED      :  381
	MULT-MATCH :  20
	NO-MATCH   :  12
	NO-PRED    :  586
	NO-DATA    :  1
	####################

	UPDAING ADDRESS

	Adding photos
	100%
	No of place id ->381
	Permanently closed is  Arihant Institute
	Permanently closed is  Oxford Academy
	Permanently closed is  Aptech-Gurukul Centre
	Permanently closed is  Career Dynamics
	Permanently closed is  Focus Institute
	Permanently closed is  P.T. Education
	Permanently closed is  Jeet Academy
	Permanently closed is  SS Classes
	viewports for  99
	ADDING GEOCODES...
	Processed 50 rows.
	Processed 100 rows.
	Processed 150 rows.
	Processed 200 rows.
	Processed 250 rows.
	Processed 300 rows.
	Processed 350 rows.
	Processed 400 rows.
	Processed 450 rows.

	Processed 500 rows.
	Processed 550 rows.
	Processed 600 rows.
	Total precise entries: 613 out of 619
	Fetching info from FB Graph
	100%
	New Info Added from Facebook
	Details:66 Facebook Link:282 Cover:204
	Website:67 Pincode:0 Address:31 Images:234 Verified 0/282 Phone:220 Emails:0
	Writing to CSV...
	***Successfully processed 1 files.***
	1
	./output/processed_sample.csv -> updated_sample.csv
	2
	./output/processed_sample_big.csv -> updated_sample_big.csv

Error is fixed.
