### ISSUE TITLE
Make first character of all names capital

### ISSUE THREAD

**Issue by rohitmanglik** [rohitmanglik/scrap-preprocessor#46]
Some of the names in output file have first character small.

e.g.
- deori Road, laxmi Palace, Madhuvan Colony, Agra, Uttar Pradesh 282001, India : "d" and "l" over here
- agra: "a" over here
- Shop No. 5, 2nd Floor Mahatma Gandhi Road, agra, 282002, India: "a" of agra over here.

Capitalize first character of all the names.

**Comment by gupta-shantanu** [comment]
092d660 should fixes this.

**Comment by gupta-shantanu** [comment]
Please verify if this is what you wanted.

**Comment by rohitmanglik** [comment]
Except two comments in 092d660, it's working fine.
