### ISSUE TITLE
Update documentation of how to run script in background

### ISSUE THREAD

**Issue by rohitmanglik** [rohitmanglik/scrap-preprocessor#47]

**Comment by rohitmanglik** [comment]
Code is stuck after adding photos

	bitnami@ip-172-31-4-116:~/rohit/scrap-preprocessor$ python main.py > 2016102.log 2>&1 &
	bitnami@ip-172-31-4-116:~/rohit/scrap-preprocessor$ cat 2016102.log
	['./input/sample_big.csv']

	RUNNING AUTOCOMPLETE
	100%

	####################
	FIXED      :  381
	MULT-MATCH :  20
	NO-MATCH   :  12
	NO-PRED    :  586
	NO-DATA    :  1
	####################

	UPDAING ADDRESS

	Adding photos
	100%

**Comment by shubhiD** [comment]
I guess there are no such errors now?

**Comment by rohitmanglik** [comment]
I got following error while processing scrap4_mumbai.csv using updated documentation.

		   # CHANGING QUERY(3)
			NOT VERIFIED
	14      # CHANGING QUERY(1)
			# CHANGING QUERY(2)
			MATCHING STATES
			-->  St. Paul College, Mumbai Metropolitan Area, Vitthalwadi, Ulhasnagar, Maharashtra, India
			STATE MATCHED
			RES:  VERIFIED
	15      # CHANGING QUERY(1)
			MATCHING STATES
			-->  Traceback (most recent call last):
	  File "geocodertest.py", line 231, in <module>
		f.process()
	  File "geocodertest.py", line 60, in process
		self.autoComp.main(self.rows)
	  File "/home/bitnami/rohit/scrap-preprocessor/autoComplete.py", line 251, in main
		self._autoComplete()
	  File "/home/bitnami/rohit/scrap-preprocessor/autoComplete.py", line 294, in _autoComplete
		flag, prediction = self.analyze_prediction(row,address,state,True,True)
	  File "/home/bitnami/rohit/scrap-preprocessor/autoComplete.py", line 171, in analyze_prediction
		print '\t--> ',x["description"]

**Comment by shubhiD** [comment]
I think @shashwat-vik can help in this regard, he updated his code recently

**Comment by shashwat-vik** [comment]
Didn't get any errors after running for the entire file of scrap4_mumbai.csv

`2286    # CHANGING QUERY(1)
        -->  Vastra Emporium, Old Panvel, Navi Mumbai, Maharashtra 410206, India
        PINCODE PRESENCE IN PREDICTION CONFIRMED
        RES:  VERIFIED
####################
VERIFIED     :  1074
NOT VERIFIED :  1211
####################
`

**Comment by rohitmanglik** [comment]
Can you run the code again whole data set and check if any error comes? Which server are you using? 

Might be there are some configuration issues in the server. As finally script needs to be run in our server, can you please cross verify by running it over there.

**Comment by rohitmanglik** [comment]
Error persists. I  got following reply:
	bitnami@ip-172-31-4-116:~/rohit/scrap-preprocessor$ cat 201610032015.log
	['./input/scrap4_mumbai.csv', './input/scrap_rajkot_output_1.csv', './input/nagpur_output_1.csv', './input/vijayawada_output_1.csv', './input/sample_big.csv', './input/scrap_visakhapatnam.csv', './input/sample.csv', './input/scrap_thrissur_output_1.csv']

	Current file is ./input/scrap4_mumbai.csv


	RUNNING AUTOCOMPLETE
	STATE :  Maharashtra
	2       # CHANGING QUERY(1)
			# CHANGING QUERY(2)
			# CHANGING QUERY(3)
			NOT VERIFIED
	3       # CHANGING QUERY(1)
			# CHANGING QUERY(2)
			# CHANGING QUERY(3)
			NOT VERIFIED
	4       # CHANGING QUERY(1)
			# CHANGING QUERY(2)
			# CHANGING QUERY(3)
			NOT VERIFIED
	5       MATCHING STATES
			-->  IBSAR Pune, Pune, Maharashtra, India
			-->  Institute of Business Studies, Faridabad, Haryana, India
			-->  Institute of Business Studies, Meerut, Uttar Pradesh, India
			STATE MATCHED
			RES:  VERIFIED
	6       # CHANGING QUERY(1)
			# CHANGING QUERY(2)
			# CHANGING QUERY(3)
			NOT VERIFIED
	7       # CHANGING QUERY(1)
			# CHANGING QUERY(2)
			# CHANGING QUERY(3)
			MATCHING PHONE NUMBERS
			|| ORIGINAL :  ['+91 22 49433844']
			||   > NEW :  2266567716
			||   > NEW :  2224110898
			||   > NEW :  2224110879
			||   > NEW :
			||   > NEW :
			NO PHONE MATCHED
			MATCHING WEBSITE
			|| ORIGINAL :  http://jkjadhav.com
			||   > NEW :  http://www.mumbaiport.gov.in/
			||   > NEW :  http://www.mumbaibedcollege.in/
			||   > NEW :  http://www.mimr.in/
			||   > NEW :
			||   > NEW :
			NO WEBSITE MATCHED
			NOT VERIFIED
	8       # CHANGING QUERY(1)
			# CHANGING QUERY(2)
			# CHANGING QUERY(3)
			MATCHING PHONE NUMBERS
			|| ORIGINAL :  ['022 - 26055259', ' 022 - 26480348', ' 022 - 26041972', ' 9869543598', ' 9757234454']
			||   > NEW :  2226440446
			||   > NEW :  2226421271
			||   > NEW :  2226408554
			||   > NEW :  8652408878
			||   > NEW :
			NO PHONE MATCHED
			NOT VERIFIED
	9       MATCHING STATES
			-->  Karmaveer Bhaurao Patil College, Vashi, Navi Mumbai, Maharashtra, India
			STATE MATCHED
			RES:  VERIFIED
	10      # CHANGING QUERY(1)
			# CHANGING QUERY(2)
			# CHANGING QUERY(3)
			NOT VERIFIED
	11      MATCHING STATES
			-->  Mulund College of Commerce, Mumbai, Maharashtra, India
			STATE MATCHED
			RES:  VERIFIED
	12      # CHANGING QUERY(1)
			# CHANGING QUERY(2)
			# CHANGING QUERY(3)
			NOT VERIFIED
	13      # CHANGING QUERY(1)
			# CHANGING QUERY(2)
			# CHANGING QUERY(3)
			NOT VERIFIED
	14      # CHANGING QUERY(1)
			# CHANGING QUERY(2)
			MATCHING STATES
			-->  St. Paul College, Mumbai Metropolitan Area, Vitthalwadi, Ulhasnagar, Maharashtra, India
			STATE MATCHED
			RES:  VERIFIED
	15      # CHANGING QUERY(1)
			MATCHING STATES
			-->  Traceback (most recent call last):
	  File "geocodertest.py", line 231, in <module>
		f.process()
	  File "geocodertest.py", line 60, in process
		self.autoComp.main(self.rows)
	  File "/home/bitnami/rohit/scrap-preprocessor/autoComplete.py", line 251, in main
		self._autoComplete()
	  File "/home/bitnami/rohit/scrap-preprocessor/autoComplete.py", line 294, in _autoComplete
		flag, prediction = self.analyze_prediction(row,address,state,True,True)
	  File "/home/bitnami/rohit/scrap-preprocessor/autoComplete.py", line 171, in analyze_prediction
		print '\t--> ',x["description"]
	UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 1: ordinal not in range(128)
	1
	./output/processed_scrap_visakhapatnam.csv -> updated_scrap_visakhapatnam.csv
	2
	./output/processed_scrap_rajkot_output_1.csv -> updated_scrap_rajkot_output_1.csv
	3
	./output/processed_sample.csv -> updated_sample.csv
	4
	./output/processed_sample_big.csv -> updated_sample_big.csv
	5
	./output/processed_scrap4_mumbai.csv -> updated_scrap4_mumbai.csv
	6
	./output/processed_scrap_thrissur_output_1.csv -> updated_scrap_thrissur_output_1.csv
	7
	./output/processed_nagpur_output_1.csv -> updated_nagpur_output_1.csv
	8
	./output/processed_vijayawada_output_1.csv -> updated_vijayawada_output_1.csv
	bitnami@ip-172-31-4-116:~/rohit/scrap-preprocessor$

**Comment by shashwat-vik** [comment]
Verified the fix in current commit 4cd797e646c30a0b186d446dedbc8c65f45cef74

**Comment by shashwat-vik** [comment]
Updated the documentation for the concerns in the commit 6b0e7af521f21a56a821471bc2aa66ae23a88450

Ran the scripts as described by the updated documentation.
No errors in the log.
Hence closing the issue.
