### ISSUE TITLE
Transactional SMS

### ISSUE THREAD

**Issue by rohitmanglik** [rohitmanglik/scrap-preprocessor#49]
Create a new Column for Mobile number. 

Scan through the phone numbers and filter out the numbers that don't belong to mobile,

**Comment by shubhiD** [comment]
Discussion: How to verify if a number is landline or mobile? 
Suggestions please

**Comment by gupta-shantanu** [comment]
@shubhiD I guess we cannot be 100% accurate but for our purpose, 10 digit numbers > 7billion are definitely mobile numbers. We can also check if number has international code appended at the beginning and remove it. We may alternatively construct simple regex for the same.

Many mobile numbers might still be left out but, any more effort or use of external API would not make much difference.
This method would ignore mobile numbers with spaces or separators but that's because that are more likely to be landline numbers.

**Comment by rohitmanglik** [comment]
Also check for some free Carrier Lookup API - if there is some inexpensive one, we can go for it.  We cannot for anyone that charges per query.

**Comment by shubhiD** [comment]
Twilio is one such

**Comment by shubhiD** [comment]
@gupta-shantanu  making regex would be complex or going by the length of digits to say if a number is landline or mobile, though not complex but many cases might be left out as you pointed already so I guess we need something for number lookup

**Comment by rohitmanglik** [comment]
Excellent. It's free as well.

https://www.twilio.com/lookup#pricing (we just need Connection Lookup).

I also tried searching for my number and it worked great.  (Caution: you have to enter ISD code as well).

Going for third party service can actually save money for us in SMS plans.

**Comment by rohitmanglik** [comment]
If you guys also agree, we can create a separate class for this lookup. Also contribute your keys as we might again be restrained by fair usage policy.

**Comment by shubhiD** [comment]
Interesting fact whatsapp uses twilio 
One more is whitepages.com 
We have to take care of codes and have to change 0 with 91

**Comment by rohitmanglik** [comment]
As suggested by @shubhiD we can write a beautiful soap code for http://www.whitepages.com/phone/91-5692-241-887

Twilio is vrey costly for our purpose.

**Comment by gupta-shantanu** [comment]
twilio is free, right?

**Comment by rohitmanglik** [comment]
Nop! I and Shubhankar created accounts yesterday. They are not free!

**Comment by gupta-shantanu** [comment]
```
import requests
import json
print(json.loads(requests.get("https://lookups.twilio.com/v1/PhoneNumbers/%s?Type=carrier&Type=caller-name"%("91-5692-241-887"),auth=("AC086728331b2e303cda499de8e36e3ba2","2fd8e3dcad09495f4b68ba20eef63344")).text)['carrier']['type'])
```
Isn't this enough for our purpose?

**Comment by rohitmanglik** [comment]
Just in case above sites don't work out, try https://www.nexmo.com/

**Comment by gupta-shantanu** [comment]
@rohitmanglik Turns out they are giving some limited free trials to new users. As for whitepages.com, we can't use beautiful soup, the site loads content dynamically to prevent scrapping.
@shubhiD should we try Twilio with multiple trial accounts? Can you help me find max limit of the trial? Somewhere I read that it has $30 free credit but it ain't on the site.

**Comment by rohitmanglik** [comment]
Last option: https://www.google.co.in/search?q=regex+for+landline+number&oq=regex+for+landl&aqs=chrome.1.69i57j0l5.7412j0j4&sourceid=chrome&ie=UTF-8

**Comment by shubhiD** [comment]
Nexmo is paid.

**Comment by shubhiD** [comment]
@gupta-shantanu we can try with multiple trial accounts, if you are saying we get $30 as trial so we can have 6000 searches per trial account, then we have to separately verify these numbers I guess as if we will include in our main code, running it every time will be not useful.

I guess we need to do this transactional number thing once we have all the phone numbers in hand, and I suppose we should not repeat for numbers already verified. 

What say?

**Comment by rohitmanglik** [comment]
@gupta-shantanu @shubhiD I saw your comments on 6000 requests per trial account. Every row has around 2-3 entries so it means one API key will cater to ~2500 rows. 

We have 2lakh rows so it will need 80 API keys. +20 keys for testing, buffer and errors.

If I put someone from Operations team to get 100 API keys, is it possible to get them in a day? Do he need to get 100 different mobile number, which is really tough task.

**Comment by shubhiD** [comment]
@rohitmanglik  Shantanu bhaiya has found a way in which differentiating mobile number from landline number is a easy task, no money required for that

**Comment by rohitmanglik** [comment]
ohh that's great!

**Comment by shubhiD** [comment]
Some mobile numbers are starting from 91 instead of +91,Is it a issue? other than that the issue can be closed, the fix is working great

**Comment by rohitmanglik** [comment]
`2%Bad Phone number +91-890536336
4%Bad Phone number +91-+ 91- 98989 99012
19%Bad Phone number +91-79-26421298 / 99
25%Bad Phone number +91-79 - 661318
33%Bad Phone number +91-+ 91-02764-260 287
45%Bad Phone number +91-(+91)-79-26568755
67%Bad Phone number +91- - 27492592
78%Bad Phone number +91-Bhanwar Rathore +91 98250 57598
86%Bad Phone number +91-9825790129/9099984983/07940080567
89%Bad Phone number +91-9898990791 MANISH RAVAL
Bad Phone number +91-9898990793 MONA RAVAL
90%Bad Phone number +91-79-26629500 / 600
94%Bad Phone number +91-2685 4862
99%Writing to CSV...`

After analyzing above values:

a) Through this issue, we have an opportunity to improve our source contact numbers as well. Output file has contact numbers from input file, FB and Google. This means data is not consistent. Can we improve formatting of contact numbers in output files?

b) **Some** of the above values can be corrected and then saved back in claim_phone, phone2 etc columns.

**Comment by rohitmanglik** [comment]
@gupta-shantanu what's the current stats for above scenario?

**Comment by gupta-shantanu** [comment]
@shubhiD handled this in 6118960 . Few of them are very specific cases, and should be recovered manually (e.g. 79-26629500 / 600).

**Comment by shubhiD** [comment]
@gupta-shantanu  I have coded to update these numbers as well (e.g. 79-26629500 / 600)

**Comment by rohitmanglik** [comment]
Just verified final output. Final output has 91, +91. Remove these two starting char combinations and then we can close this issue.
