### ISSUE TITLE
3 unnecessary columns

### ISSUE THREAD

**Issue by rohitmanglik** [rohitmanglik/scrap-preprocessor#5]
As Superlist doesn't allow users to set following default values, create 3 columns with defaults:

map_type: Roadmap  - (Roadmap is wrong, have to get confirmation of the right value)
listing_banner_map_marker: true or yes (get it confirmed)
Listing_banner_zoom: 16

**Comment by eriktelepovsky** [comment]
listing_banner_map_marker values can be either "on" or empty string

listing_banner_map_zoom default value is 18.

listing_banner_map_type value can be one of SATELLITE, ROADMAP or HYBRID
