### ISSUE TITLE
Remove wrong email addresses

### ISSUE THREAD

**Issue by rohitmanglik** [rohitmanglik/scrap-preprocessor#52]
Some of the email addresses might be obsolete. Sending wrong email will hit our EMail score. We have to remove those obsolete email addresses from our database.

Doing it is very straight forward procedure. Refer following articles on how to do it.

https://pypi.python.org/pypi/validate_email
https://www.scottbrady91.com/Email-Verification/Python-Email-Verification-Script
https://github.com/JoshData/python-email-validator

**Comment by gupta-shantanu** [comment]
Validating email address is not supported by all SMTP servers. Only addresses belonging to standard servers like gmail can be reliably validated. Other servers like that of roboleads@mteducare.com or admissions@isc.edu.in are not behaving accordingly. For now I have added check for gmail addresses only.

**Comment by rohitmanglik** [comment]
By the way email server of roboleads@mteducare.com rejected my email just now.

**Comment by rohitmanglik** [comment]
What about yahoo and rediffmail. Some people still use these services :/

**Comment by rohitmanglik** [comment]
We have doubts in 6 out of 261 records. With good assumptions, we can say 2.5% records need to be corrected. It means just 5000 records in 200k entries. We should be able to leverage some third party APIs to correct such records.

We can leverage some third party API for such records.

**Comment by rohitmanglik** [comment]
Also script is very slow. Can you create multiple threads? We don't need API key in this case so I believe this shouldn't be an issue.

**Comment by pinakinathc** [comment]
#52
https://github.com/pinakinathc/scrap-preprocessor/pull/1/commits/f88eb095b3360c38f54e9dbf94aa3cbdef7363f1
