### ISSUE TITLE
Contact person's name

### ISSUE THREAD

**Issue by rohitmanglik** [rohitmanglik/scrap-preprocessor#7]
Currently we are unable to save Contact person's name in Contact metabox. 

Find the right way to do it from Plugin Author

**Comment by eriktelepovsky** [comment]
It is a regular textfield field with ID listing_person

**Comment by alchem9st** [comment]
Changed contact person to listing_person

**Comment by rohitmanglik** [comment]
listing_person column doesn't exist in WP Ultimate CSV Importer.

**Comment by rohitmanglik** [comment]
Posted the query at https://wordpress.org/support/topic/some-fields-are-missing-in-superlist?replies=1#post-8774084

**Comment by rohitmanglik** [comment]
This two fields may not be present in the existing records (posts/directories).   As we show the available fields by fetching data from the DB, these two fields will not appear. Create a dummy record with these two fields and set the record as draft.  Try importing the data after doing the above step.
Hope this helps -Smackcoders

listing_person appears now. However, listing_website is still missing.

**Comment by anantharam** [comment]
Both listing_website and listing_person are available in the result csv now.

**Comment by eriktelepovsky** [comment]
Btw. Add-on for WP All Import plugin was released few days ago (just to know):

https://wordpress.org/plugins/import-xml-csv-listings-to-inventor-wp/
