### ISSUE TITLE
Add more photos using Google Places API

### ISSUE THREAD

**Issue by rohitmanglik** [rohitmanglik/scrap-preprocessor#9]
We already have Latitude and Longitude.

Fetching images should be simple through Google Place Photo API : https://developers.google.com/places/web-service/photos

**Comment by abhikrsagar** [comment]
from selenium import webdriver
import os
import subprocess as sp
script_dir = os.path.dirname(os.path.realpath('__file__'))
#<-- absolute dir the script is in
rel_path = "traffic.png"
path = os.path.join(script_dir, rel_path)
#Enter the latitude and longitude of the location eg 28.6276616,77.2374855
lat=input('Enter the latitude of the place eg 28.6276616:')
lon=input('Enter the longitude of the place eg 77.2374855:')
zm=input('Enter the zooming which you want for ex 11(11x):')
zt=str(zm)
u='https://www.google.co.in/maps/@'
v=','+zt+'z/?hl=en'
url=u+str(lat)+','+str(lon)+v
#depot = DepotManager.get()
driver = webdriver.PhantomJS()
driver.set_window_size(1366,768) # set the window size that you need 
driver.get(url)
driver.save_screenshot('place.png')
driver.close()
os.startfile('traffic.png')

**Comment by rohitmanglik** [comment]
@anantharam @shubhiD Can you please check code of @abhikrsagar and let me know your comments.

Thanks

**Comment by shubhiD** [comment]
I think this code will return a map photo not the photos of the institutions

**Comment by abhikrsagar** [comment]
Ya right I have written the code to return map photo only.Can you give me a
brief of your requirement so that I can write the script accordingly

**Comment by shubhiD** [comment]
Like you are searching for the pic of IIT madras then we have to fetch all possible images under 10 would be sufficient

**Comment by abhikrsagar** [comment]
so this can be accomplished by downloading some images from the google image search of the corresponding query ri8

**Comment by shubhiD** [comment]
I had same plans, try it, although I have tried through google maps api, you try with image search but remember the google api for image search has been deprecated and there are other issues like images should be high quality aakash institute for specific location should return images based on its location

**Comment by abhikrsagar** [comment]
ya I also read that google api has been depreciated but we can use selenium to automate the image search on backend,fetch image url and then I have my web scrapper in my git repository which will dwnld the image

**Comment by shubhiD** [comment]
try it create a fork of this repo and update your code but selenium is slow but then also try we will see which method is better

**Comment by shubhiD** [comment]
I already have images through google api's we will see what results in best approach

**Comment by abhikrsagar** [comment]
sure I will try both ways.I have just started web scrapping and I was looking for some open source project where I can systematically contribute and learn and I am glad I have found the repository I was looking for so thanks for this repository

**Comment by shubhiD** [comment]
I am a contributor too!

**Comment by rohitmanglik** [comment]
@abhikrsagar @shubhiD Good to see you guys discussing. - Keep it up

@shubhiD - you said aerial view? Sounds interesting. Can you show some examples?

**Comment by shubhiD** [comment]
its just like you search in google maps for the location it returns that location with some landmarks @rohitmanglik

**Comment by rohitmanglik** [comment]
Ohh. We already have that in Google Maps on our site.

**Comment by shubhiD** [comment]
yup like the one you showed for niks academy

**Comment by rohitmanglik** [comment]
Getting following error during runniing:
list index out of range

**Comment by shubhiD** [comment]
That are for the ones for which no photos were grabbed

**Comment by shubhiD** [comment]
I can change the error output if required

**Comment by rohitmanglik** [comment]
I see. Please do so. Thanks :)

**Comment by rohitmanglik** [comment]
Verified the results.
